function fig = jnFig(w, h)
% JNFIG  Create a figure exactly w x h cm (print size), Arial, white background.
% Pair with jnAxes (per-axes style) and jnExport (vector PDF + 300-dpi PNG).
%   fig = jnFig(5.5, 3.3)   % one panel, 3-across on a double column
S = jnStyle();
fig = figure('Color','w','Units','centimeters','Position',[2 2 w h], ...
    'PaperUnits','centimeters','PaperPosition',[0 0 w h],'PaperSize',[w h], ...
    'DefaultAxesFontName',S.font,'DefaultTextFontName',S.font, ...
    'DefaultAxesFontSize',S.fs_tick,'DefaultAxesFontWeight',S.fw_tick, ...
    'DefaultAxesLineWidth',S.lw_axis,'DefaultAxesTickDir','out','DefaultAxesBox','off');
end
