function setPaperDefaults()
% SETPAPERDEFAULTS  Set MATLAB groot defaults for all paper figures.
% Call once at the top of every paper-figure script (after PS = paperStyle()).
% Eliminates repetitive:  ax.FontSize=6; ax.FontWeight='bold';
%                         ax.Box='off'; ax.TickDir='out';
% in every script — all new Axes and Text objects inherit these automatically.
%
% NOTE: LineWidth is NOT set via groot because different line types use
%       different widths (PS.lw_mean, PS.lw_trial, etc.).
PS = paperStyle();
set(groot, ...
    'DefaultAxesFontSize',   PS.fs, ...
    'DefaultAxesFontWeight', PS.fw, ...
    'DefaultAxesBox',        PS.ax_box, ...
    'DefaultAxesTickDir',    PS.ax_tickdir, ...
    'DefaultTextFontSize',   PS.fs, ...
    'DefaultTextFontWeight', PS.fw);
end
